In [174]:
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
%matplotlib inline

## Make a list of observed files

In [230]:
SubStoreFilePaths = []
mydir = r'C:\Users\cflhxb\Dropbox\APSIMPotato\Observed\SubStorValidationData\experiments'
for file in os.listdir(mydir):
    if file.endswith('.xlsx'):
        SubStoreFilePaths.append(os.path.join(mydir, file))

## Make a list of data frames to work through

In [231]:
SubStoreFiles = []
for ObsTable in SubStoreFilePaths:
    SubStoreFiles.append(pd.read_excel(ObsTable,na_values=-99))

In [211]:
def IsMetaDataRow(RowVal):
    if isinstance(RowVal, str):
        if 'Metadata' in RowVal:
            return True
        else:
            return False
    else: 
        return False

def IsTimeSeriesRow(RowVal):
    if isinstance(RowVal, str):
        if 'Time' in RowVal:
            return True
        else:
            return False
    else: 
        return False
    
def IsSummaryRow(RowVal):
    if isinstance(RowVal, str):
        if 'Summary' in RowVal:
            return True
        else:
            return False
    else:
        return False
    
        
def IsManagementRow(RowVal):
    if isinstance(RowVal, str):
        if 'Management' in RowVal:
            return True
        else:
            return False
    else:
        return False

## Go through each data file and put the experiment name and treatments into a index frame

In [202]:
TreatList = []
for ObsTable in SubStoreFiles:
    MetaDataMask = [IsMetaDataRow(x) for x in ObsTable.iloc[:,0]]
    FirstTreatRowPos = ObsTable.iloc[MetaDataMask].index[0] + 5
    TreatRow = FirstTreatRowPos
    while isinstance(ObsTable.iloc[TreatRow,0], int):
        TreatNumber = ObsTable.iloc[TreatRow,0]
        ExpName = str(ObsTable.iloc[TreatRow][3] )
        TreatName = ExpName + str(ObsTable.iloc[TreatRow][5])
        TreatName = TreatName.replace(' ','')
        TreatName = TreatName.replace('=','')
        TreatName = TreatName.replace('%','')
        TreatList.append([ExpName,TreatNumber,TreatName])
        TreatRow +=1
TreatmentIndex = pd.DataFrame(data=TreatList, 
                          columns = ['ExpName','TreatNumber','TreatName'])
TreatmentIndex.set_index('TreatName',inplace=True)

In [179]:
TreatmentIndex

                               ExpName  TreatNumber
TreatName
AMNG9901VariedadCapiro        AMNG9901            1
AUCB7001Radiation100Deficit2  AUCB7001            1
AUCB7001Radiation79Deficit2   AUCB7001            2
AUCB7001Radiation66Deficit2   AUCB7001            3
AUHU9601N_Fertilizer90kg/ha   AUHU9601            2
AUHU9801N_Fertilizer150kg/ha  AUHU9801            1
CHBE9801OTC_CF_CF_98          CHBE9801            1
CHBE9801OTC_NF_NF_98          CHBE9801            2
CHBE9801OTC_NF++_NF_98        CHBE9801            3
CHBE9801AA_98                 CHBE9801            6
CHBE9801OTC_CF_CF_99          CHBE9801            7
CHBE9801OTC_NF_NF_99          CHBE9801            8
CHBE9801OTC_NF++_NF_99        CHBE9801            9
CHBE9801AA_99                 CHBE9801           12
CHFI9801OTC_AA_AA_98          CHFI9801            1
CHFI9801OTC_NF_NF_98          CHFI9801            2
CHFI9801OTC_NF+_NF_99         CHFI9801            3
CHFI9801OTC_AA_AA_99          CHFI9801            4
CHFI9801OTC_NF_NF_99          CHFI9801            5
CHGR9801OTC_NF_CF_98          CHGR9801            1
CHGR9801OTC_NF+_CF_98         CHGR9801            2
CHGR9801OTC_NF++_CF_98        CHGR9801            3
CHGR9801FACE_FACE_CF_98       CHGR9801            8
CHGR9801FACE_FACE+_CF_98      CHGR9801            9
CHGR9801OTC_NF_CF_99          CHGR9801           10
CHGR9801OTC_NF+_CF_99         CHGR9801           11
CHGR9801OTC_NF++_CF_99        CHGR9801           12
CHGR9801FACE_FACE_CF_99       CHGR9801           17
CHGR9801FACE_FACE+_CF_99      CHGR9801           18
CHIE9801OTC_NF_NF_98          CHIE9801            1
...                                ...          ...
PULU0801I20N135               PULU0801           22
PULU0801I20N180               PULU0801           23
PULU0801I20N225               PULU0801           24
SCDU8401MarPip_N0_84          SCDU8401            1
SCDU8401MarPip_N240_84        SCDU8401            2
SCDU8401MarPip_N0_85          SCDU8401            3
SCDU8401MarPip_N240_85        SCDU8401            4
SCDU8401MarPip_wet_86         SCDU8401            5
SCDU8401MarPip_dry_86         SCDU8401            6
SCDU8401MarPip_wet_87         SCDU8401            7
SCDU8401MarPip_dry_87         SCDU8401            8
SFUF1001Pivot19(2010)         SFUF1001            1
SFUF1001Pivot12(2011)         SFUF1001            2
SFUF1001Pivot17(2011)         SFUF1001            3
SFUF1001Pivot10(2012)         SFUF1001            4
SFUF1001Pivot18(2012)         SFUF1001            5
SFUF1001Pivot12(2013)         SFUF1001            6
UFHA10012011_F1_3             UFHA1001           19
UFHA10012011_F1_5             UFHA1001           21
UFHA10012011_F2_3             UFHA1001           27
UFHA10012011_F2_5             UFHA1001           29
UFHA10012011_F3_3             UFHA1001           35
UFHA10012011_F3_5             UFHA1001           37
UFSF0101North_Farmer_2001     UFSF0101            1
UFSF0101South_New_2001        UFSF0101            2
UFSF0101North_Farmer_2002     UFSF0101            3
UFSF0101South_New_2002        UFSF0101            4
UFSF0101All_2003              UFSF0101            5
USBE0301B                     USBE0301            1
USBE0301D                     USBE0301            2

[222 rows x 2 columns]

## Find the column headers for observed data and and add them into a column index

In [12]:
ColumnHeaders = ['SimulationName','Clock.Today','TreatmentNumber']
for ObsTable in SubStoreFiles:
    TimeSeriesMask = [IsTimeSeriesRow(x) for x in ObsTable.iloc[:,0]]
    ColumnIndexRow = ObsTable.iloc[TimeSeriesMask].index[0] + 3
    ObsTable.iloc[ColumnIndexRow,0] = u'TreatmentNumber'
    ObsTable.iloc[ColumnIndexRow,1] = u'Clock.Today'
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('!','')
        member +=1
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('Ad','AD')
        member +=1
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('TUNA','PNAD')
        member +=1
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('UN%H','UN%D')
        member +=1
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('UYAFH','UYAD')
        member +=1
    member = 0
    for x in ObsTable.iloc[ColumnIndexRow].values:
        if isinstance(x, str):
            ObsTable.iloc[ColumnIndexRow,member] = x.replace('UYFAD','UYAD')
        member +=1
    
    ObsList = ObsTable.iloc[ColumnIndexRow,1:].dropna().values
    ObsList = [str(ObsList[x]) for x in range(len(ObsList))]
    #ObsList = [ObsList[x].replace('!','') for x in range(len(ObsList))]
    
    ColumnHeaders = list(set().union(ColumnHeaders, ObsList))

In [13]:
ColumnHeaders.append('Experiment')
ColumnHeaders

['SWAD',
 'CNAD',
 'LAID',
 'TreatmentNumber',
 'NI2D',
 'SimulationName',
 'SNAD',
 'SW2D',
 'Clock.Today',
 'SW3D',
 'NH1D',
 'NUPC',
 'PNAD',
 'NI4D',
 'UN%D',
 'LN%D',
 'NH2D',
 'NH3D',
 'HIAD',
 'DWAD',
 'SN%D',
 'CN%D',
 'TWAD',
 'TDWA',
 'LWAD',
 'NI3D',
 'NI1D',
 'RNAD',
 'CWAD',
 'SW4D',
 'UNAD',
 'RN%D',
 'UYAD',
 'UWAD',
 'LNAD',
 'NH4D',
 'RWAD',
 'CYAD',
 'SW1D',
 'Experiment']

## Make an empty dataframe to merge all of the data into

In [14]:
ObsData = pd.DataFrame(columns = ColumnHeaders)
HeaderInfo = pd.DataFrame(columns = ['Definitions','Units','Code'])

## Step through each datatable and put the data into the merged table

In [88]:
Count = 0
CleanTabs = []
for ObsTable in SubStoreFiles:
    #Make a data frame with the treatment indexs for this table
    MetaDataMask = [IsMetaDataRow(x) for x in ObsTable.iloc[:,0]]
    FirstTreatRowPos = ObsTable.iloc[MetaDataMask].index[0] + 5
    TreatRow = FirstTreatRowPos
    TreatNumbers = []
    TreatNames = []
    while isinstance(ObsTable.iloc[TreatRow,0], int):
        TreatName = str(ObsTable.iloc[TreatRow,3] ) + str(ObsTable.iloc[TreatRow,5])
        TreatName = TreatName.replace(' ','')
        TreatName = TreatName.replace('=','')
        TreatName = TreatName.replace('%','')
        TreatNames.append([TreatName])
        TreatNumbers.append(ObsTable.iloc[TreatRow,0])
        TreatRow +=1
    TreatIndex = pd.DataFrame(index = TreatNumbers,
                              data=TreatNames,
                              columns=['TreatmentName'])
    #Find the observed data for this table
    TimeSeriesMask = [IsTimeSeriesRow(x) for x in ObsTable.iloc[:,0]]
    ColumnIndexRow = ObsTable.iloc[TimeSeriesMask].index[0] + 3
    FirstObsRowPos = ObsTable.iloc[TimeSeriesMask].index[0] + 4
          
    #Make a Dataframe with the observed data for this experiment
    Columns = ObsTable.iloc[ColumnIndexRow].values
    CleanTable = pd.DataFrame(data = ObsTable.iloc[FirstObsRowPos:].values,
                             columns = Columns)
    CleanTable.dropna(axis = 0, how='all',inplace=True)
    CleanTable.dropna(axis = 1, how='all',inplace=True)
    CleanTable.ix[:,'SimulationName'] = [TreatIndex.ix[x,'TreatmentName'] for x in CleanTable.ix[:,'TreatmentNumber'].values]
    CleanTabs.append(CleanTable)
    Headers = pd.DataFrame(data = ObsTable.iloc[FirstObsRowPos-3:FirstObsRowPos].transpose().values,
                          columns = ['Definitions','Units','Code'] )
    HeaderInfo = HeaderInfo.append(Headers,ignore_index=True)
    Count +=1

In [89]:
for Tab in CleanTabs:
    ObsData = ObsData.append(Tab.ix[:,ColumnHeaders])

In [90]:
ObsData.ix[:,'Clock.Today']

0              1999-06-04
1              1999-06-17
2              1999-06-30
3              1999-07-13
4              1999-07-26
5              1999-08-08
6              1999-08-22
7              1999-09-05
8              1999-09-19
0     1970-10-19 00:00:00
1     1970-10-26 00:00:00
2     1970-11-02 00:00:00
3     1970-11-09 00:00:00
4     1970-11-16 00:00:00
5     1970-11-23 00:00:00
6     1970-11-30 00:00:00
7     1970-12-07 00:00:00
8     1970-12-14 00:00:00
9     1970-12-22 00:00:00
10    1970-10-19 00:00:00
11    1970-10-26 00:00:00
12    1970-11-02 00:00:00
13    1970-11-09 00:00:00
14    1970-11-16 00:00:00
15    1970-11-23 00:00:00
16    1970-11-30 00:00:00
17    1970-12-07 00:00:00
18    1970-12-14 00:00:00
19    1970-12-22 00:00:00
20    1970-10-19 00:00:00
             ...
55    2003-05-06 00:00:00
56    2003-01-23 00:00:00
57    2003-01-28 00:00:00
58    2003-02-04 00:00:00
59    2003-02-18 00:00:00
60    2003-02-25 00:00:00
61    2003-03-04 00:00:00
62    2003-03-11 00:00:00
63    2003-03-18 00:00:00
64    2003-03-25 00:00:00
65    2003-04-01 00:00:00
66    2003-04-08 00:00:00
67    2003-04-15 00:00:00
68    2003-04-22 00:00:00
69    2003-04-29 00:00:00
70    2003-05-06 00:00:00
71    2003-05-13 00:00:00
72    2003-05-20 00:00:00
0     2003-05-22 00:00:00
1     2003-05-30 00:00:00
2     2003-06-12 00:00:00
3     2003-07-01 00:00:00
4     2003-07-22 00:00:00
5     2003-08-19 00:00:00
6     2003-05-22 00:00:00
7     2003-05-30 00:00:00
8     2003-06-12 00:00:00
9     2003-07-01 00:00:00
10    2003-07-22 00:00:00
11    2003-08-19 00:00:00
Name: Clock.Today, dtype: object

In [91]:
SubStoreObservations = ObsData
SubStoreObservations.ix[:,'Clock.Today'] = pd.to_datetime(SubStoreObservations.ix[:,'Clock.Today'])
SubStoreObservations.ix[:,'Experiment'] = [TreatmentIndex.ix[x,'ExpName'] for x in SubStoreObservations.ix[:,'TreatmentNumber']]
SubStoreObservations.drop('HIAD',inplace=True,axis=1)

In [92]:
ColTranslation = [ 'Potato.AboveGroundLive.NConc',
 'Potato.AboveGroundLive.N',
 'Potato.AboveGroundLive.Wt',
 'Potato.AboveGroundLive.FWt',
 'Clock.Today',
 'Potato.AboveGroundDead.Wt',
 'Experiment',                 
 'Potato.Leaf.LAI',
 'Potato.Leaf.Live.NConc',
 'Potato.Leaf.Live.N',
 'Potato.Leaf.Live.Wt',
 'Soil.SoilNitrogen.NH4ppm(1)',
 'Soil.SoilNitrogen.NH4ppm(2)',
 'Soil.SoilNitrogen.NH4ppm(3)',
 'Soil.SoilNitrogen.NH4ppm(4)',
 'Soil.SoilNitrogen.NO3ppm(1)',
 'Soil.SoilNitrogen.NO3ppm(2)',
 'Soil.SoilNitrogen.NO3ppm(3)',
 'Soil.SoilNitrogen.NO3ppm(4)',
 'Potato.Total.N',
 'Potato.TotalLive.N',
 'Potato.Root.NConc',
 'Potato.Root.N',
 'Potato.Root.Wt',
 'Potato.Stem.NConc',
 'Potato.Stem.N',
 'Soil.SoilWater.SW(1)',
 'Soil.SoilWater.SW(2)',
 'Soil.SoilWater.SW(3)',
 'Soil.SoilWater.SW(4)',
 'Potato.Stem.Wt',
 'SimulationName',
 'TDWA',
 'TWAD',
 'TreatmentNumber',
 'Potato.Tuber.Live.NConc',
 'Potato.Tuber.N',
 'Potato.Tuber.Wt',
 'Potato.Tuber.LiveFWt']

In [93]:
HeaderInfo = HeaderInfo.dropna()
HeaderInfo = HeaderInfo.drop_duplicates(subset='Code')
HeaderInfo.ix[1200,:] = ['Experiment','',u'Experiment']
HeaderInfo.ix[1201,:] = ['SimulationName','',u'SimulationName']
HeaderInfo.sort_values(by='Code',inplace=True)
HeaderInfo.ix[:,'VariableName'] = ColTranslation

In [94]:
HeaderInfo

,Definitions,Units,Code,VariableName
49,Tops (ie.canopy) N,%,CN%D,Potato.AboveGroundLive.NConc
50,Tops N,kg/ha,CNAD,Potato.AboveGroundLive.N
10,Tops(leaf+stem) dry weight,kg [dm]/ha,CWAD,Potato.AboveGroundLive.Wt
64,Tops(leaf+stem) fresh weight,Mg [fm]/ha,CYAD,Potato.AboveGroundLive.FWt
1,Observation date,yyyy-mm-dd,Clock.Today,Clock.Today
7,Dead_material_dry_weight,kg [dm]/ha,DWAD,Potato.AboveGroundDead.Wt
1200,Experiment,,Experiment,Experiment
8,leaf area index,m2/m2,LAID,Potato.Leaf.LAI
218,Leaf N,%,LN%D,Potato.Leaf.Live.NConc
46,Leaf N,kg/ha,LNAD,Potato.Leaf.Live.N
6,Leaf dry weight,kg [dm]/ha,LWAD,Potato.Leaf.Live.Wt
229,NH4 soil layer 1,ug[N]/g soil,NH1D,Soil.SoilNitrogen.NH4ppm(1)
230,NH4 soil layer 2,ug[N]/g soil,NH2D,Soil.SoilNitrogen.NH4ppm(2)
231,NH4 soil layer 3,ug[N]/g soil,NH3D,Soil.SoilNitrogen.NH4ppm(3)
232,NH4 soil layer 4,ug[N]/g soil,NH4D,Soil.SoilNitrogen.NH4ppm(4)
225,NO3 soil layer 1,ug[N]/g soil,NI1D,Soil.SoilNitrogen.NO3ppm(1)
226,NO3 soil layer 2,ug[N]/g soil,NI2D,Soil.SoilNitrogen.NO3ppm(2)
227,NO3 soil layer 3,ug[N]/g soil,NI3D,Soil.SoilNitrogen.NO3ppm(3)
228,NO3 soil layer 4,ug[N]/g soil,NI4D,Soil.SoilNitrogen.NO3ppm(4)
791,N_uptake,kg/ha,NUPC,Potato.Total.N
51,Plant N,kg/ha,PNAD,Potato.TotalLive.N
94,Root N,%,RN%D,Potato.Root.NConc
91,Root N,kg/ha,RNAD,Potato.Root.N
9,Root_dry_weight,kg/ha,RWAD,Potato.Root.Wt
219,Stem N,%,SN%D,Potato.Stem.NConc
48,Stem N,kg/ha,SNAD,Potato.Stem.N
233,soil water soil layer 1,cm3/cm3,SW1D,Soil.SoilWater.SW(1)
234,soil water soil layer 2,cm3/cm3,SW2D,Soil.SoilWater.SW(2)
235,soil water soil layer 3,cm3/cm3,SW3D,Soil.SoilWater.SW(3)
236,soil water soil layer 4,cm3/cm3,SW4D,Soil.SoilWater.SW(4)
5,Stem_dry_weight,kg [dm]/ha,SWAD,Potato.Stem.Wt
1201,SimulationName,,SimulationName,SimulationName
86,Tops_roots_storage_d_wt,kg/ha,TDWA,TDWA
2,Tops_roots_storage_d_wt,kg/ha,TWAD,TWAD
0,! Definitions,! Units,TreatmentNumber,TreatmentNumber
92,Tuber N at harvest,%,UN%D,Potato.Tuber.Live.NConc
47,Tuber N,kg/ha,UNAD,Potato.Tuber.N
4,Tuber dry weight,kg [dm]/ha,UWAD,Potato.Tuber.Wt
3,Tuber fresh weight,Mg [fw]/ha,UYAD,Potato.Tuber.LiveFWt

In [95]:
SubStoreObservations.sort_index(axis=1,inplace=True)
SubStoreObservations.columns = HeaderInfo.ix[:,'VariableName'].values
SubStoreObservations.set_index(['SimulationName','Clock.Today'],inplace=True)
SubStoreObservations.ix[:,'PlantandHarvest.Script.FinalTag'] = ''
Sorted = SubStoreObservations.sort_index()

In [96]:
Simulations = SubStoreObservations.index.get_level_values(0)
for Sim in Simulations:
    Finalkey = (Sim,SubStoreObservations.ix[Sim].ix[-1:,:].index[0])
    SubStoreObservations.ix[Finalkey,'PlantandHarvest.Script.FinalTag'] = 'yield'

In [97]:
SubStoreObservations.to_excel('C:\Users\cflhxb\Dropbox\APSIMPotato\Observed\SubStoreObservationsTest.xlsx',
                              merge_cells=False)

## Find the column headers for observed data and and add them into a column index

In [232]:
ColumnHeaders = ['SimulationName','TreatmentNumber']
for ObsTable in SubStoreFiles:
    SummaryMask = [IsSummaryRow(x) for x in ObsTable.iloc[:,0]]
    ColumnIndexRow = ObsTable.iloc[SummaryMask].index[0] + 3
    ObsTable.iloc[ColumnIndexRow,0] = u'TreatmentNumber'
    
    SumList = ObsTable.iloc[ColumnIndexRow,1:].dropna().values
    SumList = [str(SumList[x]) for x in range(len(SumList))]
        
    ColumnHeaders = list(set().union(ColumnHeaders, SumList))
    #ColumnHeaders = ColumnHeaders[ColumnHeaders != '!']

In [233]:
ColumnHeaders = list(np.asarray(ColumnHeaders)[np.asarray(ColumnHeaders) != '!'])
ColumnHeaders.append('Experiment')
ColumnHeaders.append('PDATE')

## Make an empty dataframe to merge all of the data into

In [245]:
SumData = pd.DataFrame(columns = ColumnHeaders)
HeaderInfo = pd.DataFrame(columns = ['Definitions','Units','Code'])

## Step through each datatable and put the data into the merged table

In [235]:
Count = 0
CleanTabs = []
for ObsTable in SubStoreFiles:
    #Make a data frame with the treatment indexs for this table
    MetaDataMask = [IsMetaDataRow(x) for x in ObsTable.iloc[:,0]]
    FirstTreatRowPos = ObsTable.iloc[MetaDataMask].index[0] + 5
    TreatRow = FirstTreatRowPos
    TreatNumbers = []
    TreatNames = []
    while isinstance(ObsTable.iloc[TreatRow,0], int):
        TreatName = str(ObsTable.iloc[TreatRow,3] ) + str(ObsTable.iloc[TreatRow,5])
        TreatName = TreatName.replace(' ','')
        TreatName = TreatName.replace('=','')
        TreatName = TreatName.replace('%','')
        TreatNames.append([TreatName])
        TreatNumbers.append(ObsTable.iloc[TreatRow,0])
        TreatRow +=1
    TreatIndex = pd.DataFrame(index = TreatNumbers,
                              data=TreatNames,
                              columns=['TreatmentName'])
    #Find the observed data for this table
    SummaryMask = [IsSummaryRow(x) for x in ObsTable.iloc[:,0]]
    ColumnIndexRow = ObsTable.iloc[SummaryMask].index[0] + 3
    FirstObsRowPos = ObsTable.iloc[SummaryMask].index[0] + 4
    LastObsRowPos = FirstObsRowPos + len(TreatIndex)
              
    #Get the Planting Date Data
    ManagementDataMask = [IsManagementRow(x) for x in ObsTable.iloc[:,0]]
    MgmtIndexRow = ObsTable.iloc[ManagementDataMask].index[0] + 4
    FirstMgmtRowPos = MgmtIndexRow + 1
    LastMgmtRowPos = FirstMgmtRowPos + len(TreatIndex)
                          
    
    #Make a Dataframe with the observed data for this experiment
    Columns = ObsTable.iloc[ColumnIndexRow].values
    CleanTable = pd.DataFrame(data = ObsTable.iloc[FirstObsRowPos:LastObsRowPos].values,
                             columns = Columns)
    CleanTable.dropna(axis = 0, how='all',inplace=True)
    CleanTable.dropna(axis = 1, how='all',inplace=True)
    CleanTable.loc[:,'SimulationName'] = [TreatIndex.loc[x,'TreatmentName'] for x in CleanTable.loc[:,'TreatmentNumber'].values]
    CleanTable.loc[:,'PDATE'] = ObsTable.iloc[FirstMgmtRowPos:LastMgmtRowPos,1].values
    CleanTabs.append(CleanTable)
    Headers = pd.DataFrame(data = ObsTable.iloc[FirstObsRowPos-3:FirstObsRowPos].transpose().values,
                          columns = ['Definitions','Units','Code'] )
    HeaderInfo = HeaderInfo.append(Headers,ignore_index=True)
    Count +=1

In [246]:
for Tab in CleanTabs:
    SumData = SumData.append(Tab.loc[:,ColumnHeaders])

C:\Anaconda\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [249]:
SubStoreSumaries = SumData
SubStoreSumaries.loc[:,'PLDAE'] = pd.to_datetime(SubStoreSumaries.loc[:,'PLDAE'])
SubStoreSumaries.loc[:,'TDAT'] = pd.to_datetime(SubStoreSumaries.loc[:,'TDAT'])
SubStoreSumaries.loc[:,'HDATE'] = pd.to_datetime(SubStoreSumaries.loc[:,'HDATE'])
#SubStoreSumaries.loc[:,'Experiment'] = [TreatmentIndex.loc[x,'ExpName'] for x in SubStoreSumaries.loc[:,'TreatmentNumber']]

In [250]:
SubStoreSumaries

,LAIX,UYAH,UN%H,UYAFH,UNAM,H#UM,CNAM,TWAT,RNAH,BWAH,...,TreatmentNumber,UWAH,HDATE,TNAH,SimulationName,H#AM,FWAH,PLDAE,Experiment,PDATE
0,4.33,NaN,NaN,50.6,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,1999-10-15,NaN,AMNG9901VariedadCapiro,NaN,NaN,1999-04-29,NaN,1999-04-29
0,NaN,NaN,NaN,54,NaN,NaN,NaN,NaN,NaN,NaN,...,1,10044,1970-12-22,NaN,AUCB7001Radiation100Deficit2,NaN,NaN,1970-09-29,NaN,1970-08-09 00:00:00
1,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,NaN,NaN,...,2,8585,1970-12-22,NaN,AUCB7001Radiation79Deficit2,NaN,NaN,1970-09-29,NaN,1970-08-09 00:00:00
2,NaN,NaN,NaN,39,NaN,NaN,NaN,NaN,NaN,NaN,...,3,6708,1970-12-22,NaN,AUCB7001Radiation66Deficit2,NaN,NaN,1970-09-29,NaN,1970-08-09 00:00:00
0,5.95,53.8,1.32,NaN,71,NaN,166,17862,NaN,NaN,...,2,13039,1996-09-06,237,AUHU9601N_Fertilizer90kg/ha,NaN,NaN,1996-05-26,NaN,1996-04-27 00:00:00
0,6.27,92.5699,NaN,NaN,NaN,NaN,NaN,22832,NaN,NaN,...,1,18477.3,1998-09-10,NaN,AUHU9801N_Fertilizer150kg/ha,57,157,1998-05-26,NaN,1998-04-25 00:00:00
0,2,NaN,NaN,76,NaN,NaN,NaN,2373,NaN,NaN,...,1,16060.4,1998-09-14,NaN,CHBE9801OTC_CF_CF_98,NaN,25,1998-05-15,NaN,1998-05-07 00:00:00
1,2,NaN,NaN,78,NaN,NaN,NaN,2575,NaN,NaN,...,2,16096,1998-09-14,NaN,CHBE9801OTC_NF_NF_98,NaN,23,1998-05-15,NaN,1998-05-07 00:00:00
2,1,NaN,NaN,79,NaN,NaN,NaN,1480,NaN,NaN,...,3,16570.8,1998-09-14,NaN,CHBE9801OTC_NF++_NF_98,NaN,13,1998-05-15,NaN,1998-05-07 00:00:00
3,2,NaN,NaN,76,NaN,NaN,NaN,1816,NaN,NaN,...,6,17575.6,1998-08-26,NaN,CHBE9801AA_98,NaN,18,1998-05-15,NaN,1998-05-05 00:00:00
4,4,NaN,NaN,74,NaN,NaN,NaN,2849,NaN,NaN,...,7,17308.9,1999-09-07,NaN,CHBE9801OTC_CF_CF_99,NaN,27,1999-05-24,NaN,1999-05-11 00:00:00
5,3,NaN,NaN,72,NaN,NaN,NaN,3233,NaN,NaN,...,8,16866.6,1999-09-07,NaN,CHBE9801OTC_NF_NF_99,NaN,25,1999-05-24,NaN,1999-05-11 00:00:00
6,2,NaN,NaN,76,NaN,NaN,NaN,2403,NaN,NaN,...,9,18384,1999-09-07,NaN,CHBE9801OTC_NF++_NF_99,NaN,10,1999-05-24,NaN,1999-05-11 00:00:00
7,0,NaN,NaN,69,NaN,NaN,NaN,1941,NaN,NaN,...,12,16468.8,1999-09-07,NaN,CHBE9801AA_99,NaN,7,1999-05-21,NaN,1999-05-07 00:00:00
0,NaN,NaN,NaN,121.118,NaN,NaN,NaN,NaN,NaN,NaN,...,1,24919.2,1998-09-29,NaN,CHFI9801OTC_AA_AA_98,NaN,NaN,1998-06-12,NaN,1998-06-01 00:00:00
1,NaN,NaN,NaN,110.735,NaN,NaN,NaN,NaN,NaN,NaN,...,2,21500.2,1998-09-27,NaN,CHFI9801OTC_NF_NF_98,NaN,NaN,1998-06-12,NaN,1998-06-01 00:00:00
2,NaN,NaN,NaN,82.3644,NaN,NaN,NaN,NaN,NaN,NaN,...,3,21057.7,1999-09-21,NaN,CHFI9801OTC_NF+_NF_99,NaN,NaN,1999-06-08,NaN,1999-05-29 00:00:00
3,NaN,NaN,NaN,81.1866,NaN,NaN,NaN,NaN,NaN,NaN,...,4,20075.3,1999-09-21,NaN,CHFI9801OTC_AA_AA_99,NaN,NaN,1999-06-10,NaN,1999-05-29 00:00:00
4,NaN,NaN,NaN,69.987,NaN,NaN,NaN,NaN,NaN,NaN,...,5,16964,1999-09-21,NaN,CHFI9801OTC_NF_NF_99,NaN,NaN,1999-06-08,NaN,1999-05-29 00:00:00
0,NaN,NaN,NaN,41.5905,NaN,NaN,NaN,NaN,NaN,NaN,...,1,10461,1998-09-07,NaN,CHGR9801OTC_NF_CF_98,NaN,NaN,1998-05-14,NaN,1998-05-4
1,NaN,NaN,NaN,47.4141,NaN,NaN,NaN,NaN,NaN,NaN,...,2,11862.6,1998-09-07,NaN,CHGR9801OTC_NF+_CF_98,NaN,NaN,1998-05-14,NaN,1998-05-4
2,NaN,NaN,NaN,45.6454,NaN,NaN,NaN,NaN,NaN,NaN,...,3,11447.6,1998-09-07,NaN,CHGR9801OTC_NF++_CF_98,NaN,NaN,1998-05-14,NaN,1998-05-4
3,NaN,NaN,NaN,45.4993,NaN,NaN,NaN,NaN,NaN,NaN,...,8,11869.1,1998-09-14,NaN,CHGR9801FACE_FACE_CF_98,NaN,NaN,1998-05-15,NaN,1998-05-5
4,NaN,NaN,NaN,46.7668,NaN,NaN,NaN,NaN,NaN,NaN,...,9,12409.3,1998-09-14,NaN,CHGR9801FACE_FACE+_CF_98,NaN,NaN,1998-05-15,NaN,1998-05-5
5,NaN,NaN,NaN,71.7381,NaN,NaN,NaN,NaN,NaN,NaN,...,10,17400.4,1999-09-15,NaN,CHGR9801OTC_NF_CF_99,NaN,NaN,1999-05-27,NaN,1999-05-10
6,NaN,NaN,NaN,80.2616,NaN,NaN,NaN,NaN,NaN,NaN,...,11,19595.1,1999-09-15,NaN,CHGR9801OTC_NF+_CF_99,NaN,NaN,1999-05-27,NaN,1999-05-10
7,NaN,NaN,NaN,77.3506,NaN,NaN,NaN,NaN,NaN,NaN,...,12,19542.8,1999-09-15,NaN,CHGR9801OTC_NF++_CF_99,NaN,NaN,1999-05-27,NaN,1999-05-10
8,NaN,NaN,NaN,73.6382,NaN,NaN,NaN,NaN,NaN,NaN,...,17,17655.2,1999-08-27,NaN,CHGR9801FACE_FACE_CF_99,NaN,NaN,1999-05-25,NaN,1999-05-10
9,NaN,NaN,NaN,78.6166,NaN,NaN,NaN,NaN,NaN,NaN,...,18,19213.1,1999-08-27,NaN,CHGR9801FACE_FACE+_CF_99,NaN,NaN,1999-05-25,NaN,1999-05-10
0,NaN,NaN,NaN,54.0437,NaN,NaN,NaN,NaN,NaN,NaN,...,1,11860.3,1998-10-07,NaN,CHIE9801OTC_NF_NF_98,NaN,NaN,1998-05-18,NaN,1998-05-08 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,NaN,NaN,NaN,21.4,NaN,NaN,NaN,NaN,NaN,NaN,...,22,NaN,2011-01-29,NaN,PULU0801I20N135,NaN,NaN,NaT,NaN,2010-10-12 00:00:00
22,NaN,NaN,NaN,26.7,NaN,NaN,NaN,NaN,NaN,NaN,...,23,NaN,2011-01-29,NaN,PULU0801I20N180,NaN,NaN,NaT,NaN,2010-10-12 00:00:00
23,NaN,NaN,NaN,30.6,NaN,NaN,NaN,NaN,NaN,NaN,...,24,NaN,2011-01-29,NaN,PULU0801I20N225,NaN,NaN,NaT,NaN,2010-10-12 00:00:00
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,10789.2,1984-09-24,NaN,SCDU8401MarPip_N0_84,NaN,NaN,1984-05-29,NaN,1984-04-13 00:00:00
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,15318,1984-09-24,NaN,SCDU8401MarPip_N240_84,NaN,NaN,1984-05-29,NaN,1984-04-13 00:00:00
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,7787.7,1985-09-19,NaN,SCDU8401MarPip_N0_85,NaN,NaN,1985-06-03,NaN,1985-04-24 00:00:00
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,12029.5,1985-09-19,NaN,SCDU8401MarPip_N240_85,NaN,NaN,1985-06-03,NaN,1985-04-24 00:00:00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,6260.7,1986-09-23,NaN,SCDU8401MarPip_wet_86,NaN,NaN,1986-06-15,NaN,1986-05-15 00:00:00
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,10142.6,1986-09-23,NaN,SCDU8401MarPip_dry_86,NaN,NaN,1986-06-15,NaN,1986-05-15 00:00:00
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7,7564.9,1987-09-15,NaN,SCDU8401MarPip_wet_87,NaN,NaN,1987-04-06,NaN,1987-04-29 00:00:00
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,13431.6,1987-09-15,NaN,SCDU8401MarPip_dry_87,NaN,NaN,1987-04-06,NaN,1987-04-29 00:00:00
0,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,2010-05-20,NaN,SFUF1001Pivot19(2010),NaN,NaN,2010-03-15,NaN,2010-02-10 00:00:00
1,NaN,NaN,NaN,30,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,2011-04-28,NaN,SFUF1001Pivot12(2011),NaN,NaN,2011-02-26,NaN,2011-01-28 00:00:00
2,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,2011-05-20,NaN,SFUF1001Pivot17(2011),NaN,NaN,2011-03-03,NaN,2011-02-12 00:00:00
3,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN,NaN,NaN,...,4,NaN,2012-05-02,NaN,SFUF1001Pivot10(2012),NaN,NaN,2012-02-20,NaN,2012-01-31 00:00:00
4,NaN,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,NaN,...,5,NaN,2003-05-06,NaN,SFUF1001Pivot18(2012),NaN,NaN,2012-03-09,NaN,2012-02-19 00:00:00
5,NaN,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,NaN,...,6,NaN,2013-05-20,NaN,SFUF1001Pivot12(2013),NaN,NaN,2013-03-06,NaN,2013-02-14 00:00:00
0,NaN,NaN,NaN,NaN,104.566,NaN,NaN,NaN,NaN,NaN,...,19,6103.51,2011-04-18,NaN,UFHA10012011_F1_3,NaN,NaN,2011-02-12,NaN,2011-01-12 00:00:00
1,NaN,NaN,NaN,NaN,94.2131,NaN,NaN,NaN,NaN,NaN,...,21,6132.49,2011-04-18,NaN,UFHA10012011_F1_5,NaN,NaN,2011-02-12,NaN,2011-01-12 00:00:00
2,NaN,NaN,NaN,NaN,86.688,NaN,NaN,NaN,NaN,NaN,...,27,7033.22,2011-04-27,NaN,UFHA10012011_F2_3,NaN,NaN,2011-02-14,NaN,2011-01-19 00:00:00
3,NaN,NaN,NaN,NaN,98.5431,NaN,NaN,NaN,NaN,NaN,...,29,7098.56,2011-04-27,NaN,UFHA10012011_F2_5,NaN,NaN,2011-02-14,NaN,2011-01-19 00:00:00
4,NaN,NaN,NaN,NaN,130.793,NaN,NaN,NaN,NaN,NaN,...,35,8068.55,2011-04-26,NaN,UFHA10012011_F3_3,NaN,NaN,2011-02-14,NaN,2011-01-20 00:00:00
5,NaN,NaN,NaN,NaN,132.595,NaN,NaN,NaN,NaN,NaN,...,37,7706.25,2011-04-26,NaN,UFHA10012011_F3_5,NaN,NaN,2011-02-14,NaN,2011-01-20 00:00:00
0,NaN,NaN,1.12,38.7,NaN,NaN,NaN,NaN,NaN,NaN,...,1,7235,2001-05-04,NaN,UFSF0101North_Farmer_2001,NaN,NaN,2001-03-07,NaN,2001-02-15 00:00:00
1,NaN,NaN,1.34,33.7,NaN,NaN,NaN,NaN,NaN,NaN,...,2,4136,2001-05-04,NaN,UFSF0101South_New_2001,NaN,NaN,2001-03-07,NaN,2001-02-15 00:00:00
2,NaN,NaN,1.54,36.5,NaN,NaN,NaN,NaN,7.17,NaN,...,3,5674,2002-05-06,NaN,UFSF0101North_Farmer_2002,NaN,NaN,2002-03-10,NaN,2002-02-12 00:00:00
3,NaN,NaN,1.21,36,NaN,NaN,NaN,NaN,7.87,NaN,...,4,5069,2002-05-06,NaN,UFSF0101South_New_2002,NaN,NaN,2002-03-10,NaN,2002-02-15 00:00:00
4,NaN,NaN,1.07,35,NaN,NaN,NaN,NaN,NaN,NaN,...,5,6895,2003-05-06,NaN,UFSF0101All_2003,NaN,NaN,2003-03-05,NaN,2003-02-10 00:00:00
0,4.68294,96.1197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,22369.1,2003-08-19,NaN,USBE0301B,NaN,NaN,2003-04-20,NaN,2003-03-28 00:00:00
1,4.28935,81.1471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,19709.5,2003-08-19,NaN,USBE0301D,NaN,NaN,2003-04-20,NaN,2003-03-28 00:00:00